#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

PATH=$(npm bin):$PATH

if [ -n "$CI" ]; then
  exit 0
fi

commitlint --edit "$1"
cspell lint --no-summary --no-progress --no-must-find-files --language-id commit-msg "$1"
